config/routes.rb
Rails.application.routes.draw do
  devise_for :app_users, skip: [:sessions, :passwords, :registrations]
  devise_for :admin_users, skip: [:registrations]

  namespace :api do
    namespace :v1 do
      devise_scope :app_user do
        post 'sign_in' => 'sessions#create', :as => 'login'
      end
      match 'new_app_user' => 'app_users#create', :via => :post
      match 'update_user' => 'app_users#update_app_user', :via => :post
      match 'search_contact' => 'search_contacts#search_through_contact', :via => :post
      match 'create_meeting' => 'meeting_details#create_meeting', :via => :post
      match 'update_meeting' => 'meeting_details#update_meeting', :via => :post
      match 'update_your_location' => 'journey_updates#save_your_current_location', :via => :post
      match 'fetch_location' => 'journey_updates#fetch_others_current_location', :via => :get
      match 'meeting_history' => 'search_contacts#show_meeting_history', :via => :get
      match 'confirm_meeting' => 'meeting_details#meeting_accept_notification', :via => :get
      match 'change_password' => 'app_users#change_password', :via => :post
      match 'forget_password' => 'app_users#recover_password', :via => :post
      match 'stop_journey' => 'journey_updates#stop_journey', :via => :post
    end
  end    

  root 'home#index'
  resources :admin_users
  resources :app_users
  resources :meeting_details
  resources :journey_updates

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeetchaHalfway</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="top-notification-banner">
		<% if current_admin_user %>
    	<div><img height="150" src="<%= asset_path("meetcha_halfway_logo.png") %>" alt="Meetchahalfway"></div>
	    <div class="nav-links">
	    	<%= link_to "Admin Users", admin_users_path %>
	    	<%= link_to "App Users", app_users_path %>
	    	<%= link_to "Meeting Details", meeting_details_path %>
	    	<%= link_to "Journeys", journey_updates_path %>
	    </div>
    <% end %>
    <div class="login-status">
    	<p class="navbar-text pull-right">
				<% if admin_user_signed_in? %>
		  		Logged in as <strong><%= current_admin_user.email %></strong>.
		  		<%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
		  		<%= link_to "Logout", destroy_admin_user_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
		  		<%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
		  		<%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				<% end %>
			</p>
    </div>
</div>
<div class="alert-wrapper">
	<% if current_admin_user %>
		<% if notice %>
		  <p class="alert-banner alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert-banner alert-danger"><%= alert %></p>
		<% end %>
	<% else %>
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	<% end %>	
</div>
<%= yield %>

</body>
</html>